con_player_position_x						 = $002C
con_player_position_y						 = $002D
con_player_is_facing_left					 = $0055
con_player_is_facing_right					 = $0056
con_player_is_facing_up						 = $0057
con_player_is_facing_down					 = $0058

con_store_selected_item_id                   = $031A
con_item_invincible_potion_timer 			 = $0334
con_item_slingshot_proyectile_distance		 = $0339
con_player_current_slingshot_proyectiles     = $0338
con_item_slingshot_proyectile_direction	     = $033B

con_p1_current_fruits                        = $062D
con_p2_current_fruits                        = $062E
con_player_current_money					 = $0633
con_player_current_health                    = $0637
con_player_key	                             = $0639
con_p1_current_level						 = $063C
con_p2_current_level						 = $063D



